name: 02 - Eventos

on:
  push:
 # pull_request:
  # schedule:
   # - cron: "28 13 * * *"
  #workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "bye Word"
